### ISSUE TITLE
[feature] Clear Note Upon Successful Save

### ISSUE THREAD

**Issue by isosphere** [phildenhoff/logseq-slipbox#2]
Currently when adding a new note, the "note saved" callback does not also clear the input. If the user wants to write another note, they must manually clear the text box. 

I think we should add a button to clear the text box, and also automatically clear the note upon a successful save.

**Comment by phildenhoff** [comment]
It's like you've reached into my backlog of ideas and added them all as GitHub issues. Thank you — yes, this is an excellent idea (as are your others!)

**Comment by phildenhoff** [comment]
With 8578eaf, saving a note will clear the text box. I didn't add a button as I generally don't find the need, and adding it would require extra stuff to avoid accidental deletions.

On Mobile, if I need to clear the text box, I close & reopen the PWA I saved to my home screen. On desktop, CMD+A + Delete.

If you do really want a button, specifically, I can look at adding that!

**Comment by isosphere** [comment]
> If you do really want a button, specifically, I can look at adding that!

It's not a biggie for me, it just seems like a common UX thing. We can wait for others to ask!
